//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U88ERP0;Initial Catalog=QLQuanMiCay;User ID=sa;Password=123")]
        public string QLQuanMiCayConnectionString {
            get {
                return ((string)(this["QLQuanMiCayConnectionString"]));
            }
            set {
                this["QLQuanMiCayConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U88ERP0;Initial Catalog=QLQuanMiCay;Persist Security Info=Tru" +
            "e;User ID=sa;Password=123")]
        public string QLQuanMiCayConnectionString1 {
            get {
                return ((string)(this["QLQuanMiCayConnectionString1"]));
            }
            set {
                this["QLQuanMiCayConnectionString1"] = value;
            }
        }
    }
}
