// <auto-generated />
namespace DataFirstEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class themthongtinbangnhacungcap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themthongtinbangnhacungcap));
        
        string IMigrationMetadata.Id
        {
            get { return "202311200619245_them-thong-tin-bang-nha-cung-cap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
