// <auto-generated />
namespace DataFirstEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class them_tieu_de_cho_tin_tuc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_tieu_de_cho_tin_tuc));
        
        string IMigrationMetadata.Id
        {
            get { return "202310251123312_them_tieu_de_cho_tin_tuc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
